# Generated by Django 5.2.1 on 2025-05-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['user_id']},
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table='wishlist',
        ),
    ]
