# Generated by Django 5.2.1 on 2025-05-29 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='brand',
            table='brand',
        ),
    ]
