# Generated by Django 5.2.1 on 2025-06-11 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField(null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('movement_type', models.CharField(max_length=50, null=True)),
                ('caliber', models.CharField(max_length=20, null=True)),
                ('case_material', models.CharField(max_length=50, null=True)),
                ('dial_type', models.CharField(max_length=50, null=True)),
                ('bracelet_material', models.CharField(max_length=50, null=True)),
                ('water_resistance', models.CharField(max_length=50, null=True)),
                ('glass_type', models.CharField(max_length=50, null=True)),
                ('dimensions', models.CharField(max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('category_id', models.ManyToManyField(to='category.category')),
            ],
            options={
                'db_table': 'product',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('is_main', models.BooleanField(default=False)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product')),
            ],
            options={
                'db_table': 'product_image',
                'ordering': ['product'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand_id'], name='product_brand_i_406765_idx'),
        ),
    ]
