# Generated by Django 5.2.1 on 2025-05-28 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField(null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('movement_type', models.CharField(max_length=50, null=True)),
                ('caliber', models.CharField(max_length=20, null=True)),
                ('case_material', models.CharField(max_length=50, null=True)),
                ('dial_type', models.CharField(max_length=50, null=True)),
                ('bracelet_material', models.CharField(max_length=50, null=True)),
                ('water_resistance', models.CharField(max_length=50, null=True)),
                ('glass_type', models.CharField(max_length=50, null=True)),
                ('dimensions', models.CharField(max_length=50, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('brand_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='brand.brand')),
                ('category_id', models.ManyToManyField(to='category.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('is_main', models.BooleanField(default=False)),
                ('product_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product')),
            ],
        ),
    ]
