# Generated by Django 5.2.1 on 2025-05-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand', '0002_alter_brand_options_alter_brand_table'),
        ('category', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['product_id']},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand_id'], name='product_brand_i_406765_idx'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='productimage',
            table='product_image',
        ),
    ]
