# Generated by Django 5.2.1 on 2025-05-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['cart']},
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart'], name='cart_cart_id_52f3c0_idx'),
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cart',
        ),
    ]
