# Generated by Django 5.2.1 on 2025-05-29 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['order_id']},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'ordering': ['user']},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user'], name='order_user_id_60f97d_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order_id'], name='order_item_order_i_808c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='useraddress',
            index=models.Index(fields=['user'], name='user_addres_user_id_0e6f41_idx'),
        ),
        migrations.AlterModelTable(
            name='order',
            table='order',
        ),
        migrations.AlterModelTable(
            name='orderitem',
            table='order_item',
        ),
        migrations.AlterModelTable(
            name='useraddress',
            table='user_address',
        ),
    ]
